note-tex:
  stage: deploy
  script:
    - source ~/.bashrc
    - make remove
    - make site
    - make clean
    - rsync -rzuv --delete build/ ${REMOTE_USER}:${REMOTE_ARTIFACTS_DIR}
  cache:
    paths:
      - build/
    key: "$CI_COMMIT_REF_SLUG"
  tags:
    - latex
    - typst
    - shell
  except:
    changes:
      - README.md
      - LICENSE
      - .git/*
      - .gitignore