note-tex:
  stage: deploy
  script:
    - source ~/.bashrc
    - make all
    - make clean
    - rsync -rzuv --delete build/ ${REMOTE_USER}:${REMOTE_ARTIFACTS_DIR}
  artifacts:
    paths:
      - build/*
    expire_in: 1 week
  cache:
    paths:
      - build/
    key: "$CI_COMMIT_REF_SLUG"
  tags:
    - latex
    - typst
    - shell
  except:
    changes:
      - README.md
      - LICENSE
      - .git/*
      - .gitignore