note-tex:
  stage: deploy
  script:
    - source ~/.bashrc
    - make all
    - make clean
  artifacts:
    paths:
      - build/*
  cache:
    paths:
      - build/
    key: "$CI_COMMIT_REF_SLUG"
  except:
    changes:
      - README.md
      - LICENSE