name: Deploy To Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    container: ghcr.io/adamanteye/typst:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          git config --global safe.directory "*"
          make remove
          make union
          make remove
      - name: Minify
        run: |
          minify -i build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
