name: Deploy To Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  build:
    name: Build font and generate build directory
    runs-on: ubuntu-latest
    container: ghcr.io/adamanteye/typst:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          git config --global safe.directory "*"
          make remove
          make font
          make remove
      - name: Minify
        run: |
          minify -i build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/
          retention-days: 1

  deploy:
    name: Deploy to Cloudflare Pages
    needs: build
    runs-on: ubuntu-latest
    container: node:alpine
    environment: production
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-output
          path: build/
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
