name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [self-hosted, linux, docker, perf]
    environment: production
    container:
      image: ghcr.io/adamanteye/typst:latest
      env:
        HTTP_PROXY: http://host.docker.internal:10801
        HTTPS_PROXY: http://host.docker.internal:10801
      volumes:
        - /srv/note:/srv/note:rw
      options: --add-host=host.docker.internal:host-gateway
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Reset symlink
        run: |
          rm -rf build
          ln -s /srv/note build
      - name: Build
        run: |
          git config --global safe.directory "*"
          make remove
          make site -j$(nproc)
          make remove
      - name: Minify
        run: |
          minify -i build
      - name: Deploy to cloudlfare pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
