name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [self-hosted, linux, docker]
    container:
      image: ghcr.io/adamanteye/typst:latest
      env:
        HTTP_PROXY: http://host.docker.internal:10801
        HTTPS_PROXY: http://host.docker.internal:10801
      volumes:
        - /srv/note:/srv/note:rw
      options: --add-host=host.docker.internal:host-gateway
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore Cache
        run: |
          rsync -azu --delete --checksum ${{ secrets.ARTIFACTS_DIR }} build/
      - name: Build
        run: |
          git config --global safe.directory "*"
          make remove
          make site -j$(nproc)
          minify -ars -o . build
      - name: Deploy
        run: |
          rsync -rzuhv --delete --checksum build/ ${{ secrets.ARTIFACTS_DIR }}
