name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [self-hosted, linux, typst, web-service] 
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache
        run: |
          rsync -azu --delete ${{ secrets.ARTIFACTS_DIR }} build/
      - name: Build
        run: |
          make remove
          make site
          minify -ars -o . build
      - name: Deploy
        run: |
          rsync -rzuhv --delete build/ ${{ secrets.ARTIFACTS_DIR }}
