name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [self-hosted, linux, typst, web-service]
    container:
      image: ghcr.io/adamanteye/typst:latest
      volumes:
        - /srv/note:/srv/note:rw
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore Cache
        run: |
          rsync -azu --delete --checksum ${{ secrets.ARTIFACTS_DIR }} build/
      - name: Build
        run: |
          make remove
          make site
          minify -ars -o . build
      - name: Deploy
        run: |
          rsync -rzuhv --delete --checksum build/ ${{ secrets.ARTIFACTS_DIR }}
